### ISSUE TITLE
Invalid code coverage with multine function call

### ISSUE THREAD

**Issue by jfilla** [nette/tester#383]
- bug report? yes
- feature request? no
- version: 2.0.0 also reproduced with dev-master 8cf24cf

### Description
This code
```php 
class A
{
	public function b()
	{
		$x1 = 1;
		$x2 = 2;
		$x3 = 3;
		return $this->c(
			$x1,
			$x2,
			$x3
		);
	}
	private function c($x1, $x2, $x3)
	{
		return $x1 + $x2 + $x3;
	}
}
```
tested by this test
```php
class ATest extends TestCase
{
	public function testC()
	{
		Assert::notEqual(NULL, (new A())->b());
	}
}

(new ATest())->run();
```
should have 100% coverage, but it has only 80%. Code coverage generated looks like this
![screenshot from 2018-01-09 11-56-48](https://user-images.githubusercontent.com/5280477/34717719-4364d056-f534-11e7-84ae-07503b6bbb69.png)

### Steps To Reproduce
Every function call aligned to multiple lines with variables as arguments.

**Comment by JanTvrdik** [comment]
xdebug or phpdbg?

**Comment by jfilla** [comment]
xdebug. phpdbg works fine.

**Comment by JanTvrdik** [comment]
Well, use phpdbg then. The tests are about 10x faster with it anyway.

**Comment by milo** [comment]
I'll verify it and will open Xdebug bug if necessary.

**Comment by jfilla** [comment]
Thanks. I`d love to use phpddbg, but in some cases I`m getting 
```
*** Error in `phpdbg': free(): invalid pointer: 0x00007f9b1d807000 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f9b207297e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f9b2073237a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f9b2073653c]
phpdbg(zend_hash_destroy+0x146)[0x5630be2a9826]
phpdbg(php_shutdown_config+0xd)[0x5630be23efdd]
phpdbg(php_module_shutdown+0x3e)[0x5630be23746e]
phpdbg(main+0x1730)[0x5630be119d20]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f9b206d2830]
phpdbg(_start+0x29)[0x5630be11a649]
``` 
```
phpdbg 0.5.0
PHP 7.0.22-0ubuntu0.16.04.1, Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.22-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
```
but it`s not subject of this issue.

**Comment by JanTvrdik** [comment]
@milo I think it's very unlikely that this will get fixed in xdebug. The bugs in coverage results produced by xdebug have been there for as long as I can remember and are probably very well known.

@jfilla Try phpdbg without xdebug.

**Comment by jfilla** [comment]
I tried disabling, then uninstalling xdebug. Also tried increasing memory limit. Still getting same error.

**Comment by milo** [comment]
Cannot verify with PHP 7.1.3 & Xdebug 2.6.0 (and in PHPDBG 0.5.0 works too). Probably fixed in Xdebug.
